### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by highvoltage** [bertoldia/gnome-shell-trash-extension#15]
This is a very nice plugin and I'd like to package it for Debian.

Could you please add a license file to specify the software's license? Otherwise I won't be able to use it.

Thanks!

**Comment by bertoldia** [comment]
Hey Jonathan,
Will do it soon, thanks.
axel.

**Comment by bertoldia** [comment]
Done in ad2911299c8bbd12088b2484c11d75a5e5fbba74

**Comment by highvoltage** [comment]
Thanks a lot! I also see some translations got added, are you considering doing a new release of the trash extension any time soon? thanks again!
